#+title: Create A Character

* Characters in Caravan
Player characters in Caravan are *Adventurers*. This means that they are people
who dive into the unknown and enter the fray without fretting overly about their
safety.

Players must create characters with the drive to go on adventures.

Nothing venturend, nothing gained.

* Character sheet
The character sheet is made up of a number of different parts, each of which
affect who your character is and their abilities within the world.

** Attributes
Attributes are about your intrinsic power and potential. You can gain (and
lose!) attribute points over time.

Attributes fall in the range of 1-6. 3-4 is an average among adventurers,
and 8 is the average amongst commoners. 1 represents complete enfeeblement
in some regard. 20 represents being the best possible, given mortal constraints.

There are three attributes:
*** Body
This attribute represents the adventurer's connection with and investment in
their physicality.

*** Mind
This attribute represents intelligence and keenness of thought, as well as
knowledge gained through experience or education.

*** Presence
This attribute represents your ability to influence others in social situations,
and how people react when you walk into a room.

** Attribute Modifiers
When rolling against an attribute, you actually roll against an attribute modifier.

Refer to the table below to convert attribute scorse to their modifiers

| Attribute Score | Modifier |
|-----------------+----------|
|               1 |       -2 |
|               2 |       -1 |
|               3 |        0 |
|               4 |        0 |
|               5 |       +1 |
|               6 |       +2 |


** Skills
Skills are ways for your character to interact with the world. Each skill uses a
combination of your abilities to determine a skill score.

If you can't find a skill to fit a particular situation, use /Improvisation/.

Each skill roll is based on three attribute modifiers, which appear in brackets
following the skill name. For example, `(BBB)` means you should make a d6 roll
with a bonus of three times the body modifier.

For example, if you have a Body Modifier of +2 and you rolled a 3, your total
would be 5.

Skills:
*** Athletics (BBB)
Athletics is your ability to exercise your raw physical prowess on the world:
run, jump, push, pull, throw -- anything like that.
*** Perception (BBM)
This is your ability to spot things that might help or harm you.
*** Performance (BBP)
This is your ability to use your body to impress or distract others.
*** Invention (BMM)
This is your ability to dream up and make gadgets, traps, and all manner of
things.
*** Improvisation (BMP)
This is your most general skill - your ability to make up solutions on the fly.
*** Intimidation (BPP)
This is your ability to make threats, explicit or otherwise.
*** Logic (MMM)
This is your ability to think through problems and discover knew knowledge.
*** Negotiation (MMP)
This is your ability to get others to meet you in the middle.
*** Investigation (MPP)
This is your ability to figure out what's going on by working a crowd.
*** Charm (PPP)
This is your ability to flatter and stun those around you.


** Class
Your character's class defines the abilities they'll have access to, weapons
they can use, and spells they can cast. In parentheses after each are their most
important attributes.

The classes are:
*** Soldier (B)
The Soldier is all about being an efficient killing machine. Soldiers move
faster, hit harder, and keep coming back swinging. Outside of combat, their
strength and endurance are of great use when it comes to surviving the harsh
desert.
*** Engineer (BM)
The Engineer views combat as a problem to be solved. Engineers find weaknesses
in their enemies and exploit them to great effect. Outside of combat, Engineers
can use their arcanomechanical skills for a variety of uses.
*** Strategist (MB)
The Strategist seeks to control the battlefield, never starting a fight they
cannot win. Strategists support and direct others to their greatest effect.
Outside of combat, Strategists strengthen and support those around them to
build an effective team.
*** Mage (M)
The Mage is all about spellcasting. Mages wrought the raw power of magic to
create terrible and devestating speels. Outside of combat, Mages afford
protection, study relics, and manage the day-to-day.
*** Cleric (MP)
The Cleric is all about devotion, Clerics take their principles in to the
fray, protecting and smiting as is their duty. Outside of battle, clerics
look after the physical and spiritual health of those around them.
*** Mystic (PM)
The Mystic is all about secrets and trickery. Mystics use their forbidden
knowledge to trick and influence enemies. Outside of battle, the Mystic
communes with the beyond to reveal hidden things.
*** Performer (P)
The Performer is all about influence. Performers stop battles before they even
start through charm and wit. Outside of battle, Performers keep their allies in
the good graces of locals.
*** Spy (PB)
The Spy is all about subterfuge. Spies target individual enemies to destroy with
alarming violence. Outside of battle, Spies coerce, steal, and eavesdrop to
gather information.
*** Knight (BP)
The Knight is all about honour and leadership. Knights lead from the front and
encourage others to follow on their quest. Outside of battle, knights keep
their team together and protect them.

* Creating a new character
** 1. Roll your attributes
Roll 3d6 and note down the result. If the total is 9 or less, reroll all the dice.
Keep rerolling until your total is more than 9. These are your attribute points.
Youa may choose to reroll once, but you MUST keep the next result with a total
higher than 9. You can choose which attributes to apply them to.

#+begin_src text
For example, if you roll a 2, a 3, and a 4, for a total of 9, you would reroll.

If you then rolled a 2, a 3, and a 6, you would keep those scores.
#+end_src


** 2. Choose a class
Choose one of the classes above. On the class page, there is a description of
how to set up your character for first level.

#+begin_src text
Following from our example above, since you have rolled one very high, one
average, and one low, you might choose to take one of the classes that
specialises in a single attribute, like the soldier, mage, or performer.

In this example let's choose the Soldier as our class.

This means we take
#+end_src

** 3. Choose your starting equipment
Take either the standard equipment on the class page, or buy equipment from the
starting equipment list up to the value of 100 gold. You do not keep any
excess gold, so spend as much as you can.

#+begin_src text
In our soldier example, let's take the standard equipment from the soldier
class page: a steel cuirass, a round wooden shield, and a short spear.
#+end_src

** 5. Describe your character
Come up with a backstory for your character (even if it's short!), and decide
what their goal is. Then, describe their physical attributes, such as their
gender, height, weight, skin colour, eye colour, hair colour and style,
and anything else you can think of.
